### ISSUE TITLE
Cannot send audio in Conversations when connected to Mumla

### ISSUE THREAD

**Issue by asterismo** [quite/mumla#2]
Hi, i noticed that when connected to a mumble server, i cannot record audio files with Conversations Jabber/XMPP client, it complains about the mic, that it cannot access the mic. This is very frustrating because the only thing to do, is disconnect from Mumla and then record the audio file, and connect back to mumla. Is this behavior normal? I think i should be able to listen to speakers in Mumla even when the app is minimized, as well as able to record an audio in another app when app is minimized and therefore not transmitting to mumble.

**Comment by asterismo** [comment]
Is this project still alive?

**Comment by quite** [comment]
Development of Mumla takes place on gitlab.com. The project does not have much resources that actively and concretely works on it, but it is certainly not dead.

I think this issue has already been filed at https://gitlab.com/quite/mumla/-/issues but if not, please do so.
