### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by asterismo** [quite/mumla#3]
Hi, i just wanted to make a feature request. It would be nice to have the ability to transmit audio when pressing the hardware PTT button with the screen locked. Zello app has this feature and helps to save battery and not being forced to being constantly unlocking the screen when talking. Zello app needs to conficure the contact/channel to be the recipient of the audio transmission when screen is locked due to the fact that there is no way to change between channels with a locked screen. This would be a great improvment to Mumla app and would help me to move away from Zello to mumble-based services.

Cheers.

**Comment by likevinyl** [comment]
I support this request, I'm a little tired of having to unlock the screen; I bought a pushbutton for ptt solely to use MUMLA and I could never use it, please add that functionality! Thnx.

**Comment by quite** [comment]
Mumla development happens on gitlab.com. I think these issues are https://gitlab.com/quite/mumla/-/issues/48 and https://gitlab.com/quite/mumla/-/merge_requests/22 . If not, please complete.
