### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by PixelP0w3r** [quite/mumla#5]
Second feature request. Can you please make the app work with navigational keys for Android devices that do not have a touch screen?

For the most part the app works well without a touch screen, except for the ability to move between channels on a server. If you could move between channels using navigation keys, and allow navigational keys to not map to PTT button so you can select a PTT button and then confirm it without a touch screen.

Those are the only two things not working with navigational keys.

**Comment by quite** [comment]
Development happens on gitlab.com. Issue copied to https://gitlab.com/quite/mumla/-/issues/78
